### ISSUE TITLE
English first

### ISSUE THREAD

**Issue by aviggiano** [r2u-io/documentation#35]
- Colocar a documentação em inglês by default

![screenshot-2021-05-15-08-08-29](https://user-images.githubusercontent.com/3029017/118358349-bdbb9680-b554-11eb-834c-53e94561a06f.png)

- Colocar tradução da língua sempre na própria lingua nativa (`Português, English, Español, 日本語, ...`)

![screenshot-2021-05-15-08-10-32](https://user-images.githubusercontent.com/3029017/118358425-1428d500-b555-11eb-8560-bec0547e4c36.png)

@r2u-io/dev

**Comment by MayaraSs** [comment]
Feito, na última atualização.
